#+TITLE: Modeling Proton Transport in Functionalized Graphene
#+AUTHOR: Abhishek Bagusetty
#+LATEX_CLASS: cmu-article
#+OPTIONS: ^:{} # make super/subscripts only when wrapped in {}
#+OPTIONS: toc:nil # suppress toc, so we can put it where we want
#+OPTIONS: tex:t
#+EXPORT_EXCLUDE_TAGS: noexport

\maketitle

* Problem Statement
Modeling of proton transport in fuel cells has been extensively studied and the limitations involved is the high temperature applications. As the proton transport involves water channels, limited presence of water would seriouly affect the performance of a fuel cells. Modeling of proton transport on the surface of a functionalized graphene would effectively provide a solution to limited hydration conditions using molecular simulations.

* Proposed Work 
Modeling of proton transport for fuel cell applications is very prominent using electronic structure calculations but restricts exploring larger system size and longer time scales. Majority of the classical simulations or the potentials doesn't describe bond-making and bond-breaking phenomena. The proposed work would systematically analyzing a reactive potential that describes bond-making and breaking. This is followed by evaluating a reactive molecular dynamics framework that would involve 

** Reactive Potential
Some of the important contributions in modeling hydrocarbon molecule based systems involving bond breaking and making has been described by reactive empirical bond order (REBO) potential. A revised potential contains improved analytic functions will be studied cite:brenner-2002-rebo and its prospective applications in understanding proton transport phenomena will be analyzed. 

** Reactive Molecular Dynamics
After studying a reactive potential, an alternate method cite:knight-2012-multis will be reviewed that involve developing a reactive molecular dynamics model that do not require predefined empirical functions. The methods involving parametering simple analytical functions of the potentials that describes proton transport in water is studied and its application to study proton transport to a functionalized graphene based system will be explored.

** Applications
Simulation of a proton exchange membrane called Nafion is studied cite:devanathan-2007-atomis-simul using classical molecular dynamics simulations. This material also involves proton transport and the review discusses the simulation details and also the concerned analysis involved in a charge transport system.


* Bibliography
# <<bibliographystyle>>
bibliographystyle:unsrt

# <<bibliography>>
bibliography:./references.bib
