#+TITLE: 24-623 2015 HM4
#+AUTHOR: Abhishek Bagusetty
#+LATEX_CLASS: cmu-article
#+OPTIONS: ^:{} # make super/subscripts only when wrapped in {}
#+OPTIONS: toc:nil # suppress toc, so we can put it where we want
#+OPTIONS: tex:t
#+EXPORT_EXCLUDE_TAGS: noexport
#+LATEX_HEADER: \usepackage[makeroom]{cancel}
#+LATEX_HEADER: \usepackage{verbatim}

\maketitle

* Problem 1
The regular equations for the velocity verlet scheme are as follows: 

  1.$v_{i}(t+\Delta t/2) = v_{i}(t) + F_{i}(t) \Delta/2m_{i}$
  2.$r_{i}(t+\Delta t) = r_{i}(t) + v_{i}(t+\Delta t/2)\Delta t$
  3.$v_{i}(t+\Delta t) = v_{i}(t+\Delta t)+ F_{i}(t+\Delta t) \Delta/2m_{i}$

With MD simulations in NVT ensemble using the Nose-Hoover thermostat, the following are the equations of motions,

  1. $\dot{r_{i}} = \mathbf{v_{i}}$
  2. $\dot{\mathbf{v_{i}}} = \mathbf{F_{i}}/m_{i} - \eta \mathbf{v_{i}}$
  3. $\eta = \frac{1}{\tau^2_{T}} \Big(\frac{T}{T_{set} -1} \Big)$

Now replacing the acceleration term with the above equations of motion.

\begin{equation}
  v_{i}(t+\Delta t/2) = v_{i}(t) + \mathbf{F_{i}(t)/m_{i}} \Delta/2
  \label{eq:eq1}
\end{equation}

\begin{equation}
F_{i}(t)/m_{i} = a_{i} \implies \dot{\mathbf{v_{i}}} = \mathbf{F_{i}}/m_{i} - \eta \mathbf{v_{i}}
\end{equation}

Now substitute the above equation in ref:eq:eq1,
\begin{equation}
\boxed{ v_{i}(t+\Delta t/2) = v_{i}(t) + [\mathbf{F_{i}}/m_{i} - \eta \mathbf{v_{i}(t)}] \Delta/2 }
\end{equation}

The step 2 for the evolution of position remains the same as the actual expression.

The Step 3 is affecte by the $F_{i}(t+\Delta t)/m_{i}$, which is the acceleration at $(t+\Delta t)$

\begin{equation}
  v_{i}(t+\Delta t) = v_{i}(t+\Delta t) + F_{i}(t+\Delta t) \Delta/2m_{i}
  \label{eq:eq2}
\end{equation}
If we replace the force term at $(t+\Delta t)$ from the Step 3 with the modified equations of motions as follows,

$ \dot{\mathbf{v_{i}(t+\Delta t)}} = \mathbf{F_{i}(t+\Delta t)}/m_{i} - \eta(t+\Delta t) \mathbf{v_{i}(t+\Delta t)} $

Substitute the above expression in ref:eq:eq2, would give

\begin{equation}
  v_{i}(t+\Delta t) = v_{i}(t+\Delta t) + [\mathbf{F_{i}(t+\Delta t)}/m_{i} - \eta(t+\Delta t) \mathbf{v_{i}(t+\Delta t)}] \Delta/2
  \label{eq:eq3}
\end{equation}

Rearraning the expression results in ,

\begin{equation}
  v_{i}(t+\Delta t) = v_{i}(t+\Delta t) + F_{i}(t+\Delta t) \Delta/(2m_{i}) - v_{i}(t+\Delta t) \eta(t+\Delta t)\Delta/2
\end{equation}


\begin{equation}
  v_{i}(t+\Delta t)\Big(1 - \eta(t+\Delta t)\Delta/2 \Big) = v_{i}(t+\Delta t) + F_{i}(t+\Delta t) \Delta/(2m_{i})
\end{equation}

\begin{equation}
\bixed{ v_{i}(t+\Delta t) = \frac{v_{i}(t+\Delta t) + F_{i}(t+\Delta t) \Delta/(2m_{i})}{1 - \eta(t+\Delta t)\Delta/2} } 
\end{equation}

* Problem 2
** a)

Average Pressure is plotted as the function of density between 950 $kg/m^3$ and 1150 $kg/m^3$. A trendline is fit and the zero pressure density is found to be at 1042.8 $kg/m^3$ which slightly varies with the density computed from the previous computations corresponding to 1053.8 $kg/m^3$.

1. Several NVT simulations are performed with NVT ensemble and Nose-Hoover thermostat and ensuring temperature of 100K is reached for every run.

2. Equlibration is completed, as judged by the lack of energy drift in the 200 units of MD simulation. $\big\langle (E-<E>) \big\rangle$ per atom is in the order of 1e-3 which indicate the energy fluctuations are very small.

Plots of energies, temeprature and pressure are shown below for a configuration approaching zero pressure NVT simulation for 200 LJ units.


* Problem 3
