#+TITLE: Molecular Simulation of Proton Transport
#+AUTHOR: Abhishek Bagusetty
#+LATEX_CLASS: cmu-article
#+OPTIONS: ^:{} # make super/subscripts only when wrapped in {}
#+OPTIONS: toc:nil # suppress toc, so we can put it where we want
#+OPTIONS: tex:t
#+EXPORT_EXCLUDE_TAGS: noexport

\maketitle

* Review - Atomistic Simulation of Nafion membrane: I. Effect of Hydration on Membrane Nanostructure 
** Abstract
The article under review is about classical molecular dynamics simulation  performed to characterize the changes in the nanostructure of Nafion membrane that is a predominantly used material for proton exchange membrane fuel cells. It is necessary that the Nafion nanostructure is sufficiently hydrated so that facilitation of proton transport is feasible. It would be of great importance, to understand the nanostructure of Nafion systematically under various hydration levels using atomistic simulations. Nafion contains a hydrophobic CF_{2} backbone and a hydrophilic sulfonic acid terminated pendent to form nanoscale domains facilitating ionic transport. It is very well known that that water loading is an important factor for proton transport membrane and hence a water loading represented by \lambda is introduced which is the total number of water molecules and hydronium ions per sulfonate group.

It is found from the earlier work that the increase of water loading lead to the formation of water clusters that gets formed dynamically and broke to establish water channels. This behavior lead to investigate the structure of excess charge solvation affecting the nanostructure of Nafion. This current work systematically studied hydration levels (\lambda = 1,3,5,7,9,11,13.5 and 20) to closely monitor the nanostructure of Nafion and also the bulk water phase and relate it to the the experiments performed in the literature.
  
** Methodology
Classical molecular dynamics simualtions are performed with DREIDING force field for Nafion. The simulation cell contained 40 SO_{3}^{-} groups seperated by 7 nonpolar -CF_{2}-CF_{2}- monomer. The equilibrium phase is done over 4 steps: (1) NPT MD simulation is performed at 300K for 10 ps. This is performed to attain appropriate density. (2) NVT MD simulation is performed for 50 ps with the temperture raised from 300K to 600K. (3) Followed by NVT simulation of 50ps at 600K. (4) NVT MD simulation for 50ps with temperature again lowered from 600K to 300K. It is important to note that the temperature is raised from 300K to 600K and then it is dropped again back to 300K. The final production runs are performed using NVE ensemble at 300K for each water loading for 2 ns  and the configurations are saved at every 0.2 ps. The step size used for the integration was 1fs. Simulations are performed using DL_POLY package with DREIDING force field for Nafion and F3C forcefield for water.

** Results
This work is mostly driven for exploring the nanostructure of Nafion membrane under various hydration levels. More specifically, distribution of water molecules and hydronium ions along the surface water and the bulk water phase is investigated. Following that, interactions between sulfonate groups and hydronium ions are extensively studied. Effect of hydration on the side chain and backbone of the Nafion nanostructure is investigated to characterize the mechanical stability and finally, distribution of hydronium ions and water molecules are computed at different water loading in both the surface and bulk water phase.

Radial distribution funtions (RDFs) are used as tools to explore the neighbouring environments around the excess charge hydronium ions. At lower water loading, water molecules and hydronium ions are found in the vicinity of sulfonate groups. This mainly driven by the electrostatic interactions between the partial charges. As the water loading increase, water finds it way between the sulfonate groups and hence changing the spatial seperation between sulfonate groups. It is also inferred that the water molecules mediate the interactions between hydronium ions and the sulfonate groups with the hydrogen bonding network. 

With the above inferences, the interactions between the hydronium ions and the sulfonate groups turned to be interesting to investigate. RDFs are plotted for the sulfur atoms (S), sulfonate oxygen (Os) atoms in the Nafion sulfonate groups with the hydronium oxygen (Oh). First, the RDF of S-S is reported for various hydration levels. It is observed that the peaks tends to become shorter and broader with increasing hydration levels. This is because sulfonate groups move away from each other with the introduction of water molecules between them. The next correlation is between Oh-Oh. The behaviour of the RDF is similar to the S-S. With the increase of water loading, the hydronium ions tends to move apart just as the sulfonate groupsmove apart. This can be attributed to the water molecules surrounding each hydronium ion increasing the distance between the hydronium ions. The next correlation is for S-Oh and Os-Oh respectively. When water molecules are introduced, the peak of the S-Oh drops this is because the water molecules are strongly correlated with the H_{3}O^{+} pulling it away from SO_{3}^{-}. This transition of H_{3}O^{+} strongly coorelated with SO_{3}^{-} moving away to water molecules can be explained by the water solvation shells around the sulfonate groups. With the increase of water, the solvation shell moves from first solvation shell to second solvation shell as observed in the RDF plots. This process is also observed in the Os-Oh RDF plot.

Effect of hydration on the nanostructure of side chain and backbone is also reported. It is already reported that, with the increase of hydration level the water molecules gets introduced between the sulfonate groups and the interactions between the hydronium and sulfonate groups are mediated through water. Information on the presence of water molecules near the vicinity of the sulfonate group, the rest of the side chain and backbone can be found as function of water loading. RDFs are plotted relating the sulfur atom, ether oxygen from the side chain and backbone carbon with the oxygen of water. The coordinate number of water molecules surrounding the sulfur atom is greater, followed by the oxygen of the ether side chain and finally even fewer with the carbon of the backbone. This will characterize the membrane into hydrophilic and hydrophobic regimes. The hydrophilic subphase accounts the sulfonate group at the end of the pendent whereas the oxygen of the ether closest to sulfonate comes under hydrophobic regime. These are characterized based on the water coordination numbers surrounding the atoms of interest.

Characterization of the features at the bulk water phase is also reported using the RDF between oxygen of water and oxygen of hydronium ion and also the number of water molecules. The RDF at various hydration levels indicate the similar behaviour as the bulk water. The number of water molecules in the hydration shell of H_{3}O^{+} and H_{2}O is calculated for various hydration levels. It is found that atleast 3 water molecules surround the ion and water with the hydrogen bonding and tends to saturate at higher water loading. By systematically varying the water loading, the experimental observations of non-diffusing hydrogen atoms have highlighted the role of H_{3}O^{+} in preventing proton transport. 

** Conclusions
Simulations are performed to investigate the effect of various hydration levels to the Nafion nanostructure. With increasing water loading, the sulfonate groups tend to move apart and hence suggesting that the polymer could be flexible. The strong interaction between hydronium ion and sulfonate groups facilitates proton hop mechanism over vehicular transport. Water molecules are mainly found to be in the vicintiy of the sulfonate groups while the ether oxygen and backbone are strongly hydrophobic. These results are validated using infrared sprectroscopy.
 
** Critical Comments
The equilibrium phase of relaxation is very trickly presented. NVT MD simulations are performed to raise the temperature from 300K to 600K and then again the temperature is dropped from 600K to 300K. It would have been more clear, if elaborate explanation about the 4 step relaxation is provided.

* Review - The Computer Simulation of Proton Transport in Water
** Abstract
This paper explicitly deals with designing the potential for performing proton transport simulations in water. As the proton hopping mechanism involves covalent bond making and breaking, it is necessary that the potentials describes these description with a finer level of accuracy. Multistate empirical valence bond (MS-EVB) model is developed for describing the behaviour of bond breaking and making process coupled with molecular dynamics simulations. Many ab-inito methods allows to perform accurate calculations to the potential energy surface for small molecules but the extension of these methods tend to be not feasible for large number of molecules. MS-EVB model considers construction of PES for chemical reactions in an accurate and in a numerically efficient manner.

** Methodology
The Hamiltonian matrix is constructed and it is diagonalized to find the ground state energy of the configuration. The functional form of the elements in the Hamiltonian matrix can be differentiated by diagonal and off-diagonal elements. The diagonal elements in the matrix can be constructed by the sum of intramolecular and intermolecular interactions between excess charge hydronium ion and water molecules. Most of these interactions can be described by harmonic (bond and angles), Morse, LJ potential and electrostatic interactions. The most important segment of constructing a hamiltonian matrix deals with off-diagonal elements that describes the transition of excess charge between water molecules. The excess charge which is a hydronium ion (H_{3}O^{+}) interacting with water molecule forms a zundel (H_{5}O_{2}^{+}) ion complex during the transition phase. This transition complex helps to build the off-diagonal elements in describing the interactions responsible to build charge transport event. The interactions between the transition complex (H_{5}O_{2}^{+}) and the rest of the water molecules with in a given distance of first solvation shell is considered for building a off-diagonal elements potential and that describes the transition of proton defect. Most of these interactions are described by the electrostatic interactions as they are non-bonded interactions. The hamiltonian is then diagonalized for the ground state energy. The equations to construct the elements of the hamiltonian matrix is given below : 

$$h_{ii} = V_{H_{3}O^{+}}^{intra} + \sum_{k=1}^{N_{H_{2}O}} V_{H_{2}O}^{intra, k} + \sum_{k=1}^{N_{H_{2}O}} V_{H_{3}O^{+}, H_{2}O}^{inter, k} + \sum_{k<k^{'}}^{N_{H_{2}O}} V_{H_{2}O}^{intra, kk^{'}} $$

$$h_{ij} = (V_{const}^{ij} + V_{ex}^{ij}). A(R_{OO},q) $$

From the above equations, $V_{const}^{ij}$ is a constant coupling term and $V_{ex}^{ij}$ describes the exchange charge interactions. Damping function $A(R_{OO,q})$ is introduced to weight the potential according the transition phase of excess charge. The variable $q$, is a proton transport coordinate which keeps a track on the location of excess charge shared between two oxygen atoms and undergoing transition. 

On the other hand, quantum trajectories are computed using centroid molecular dynamics (CMD) which involves nuclear quantum effects into the classical potential. This method is closely related to the imaginary time average of a closed Feynman path.

In classical simulations, the system was relaxed to a temperature of 300K for 40 ps followed by NVE ensemble MD simulation of 100ps. The time step used is 0.5fs and a standard verlet algorithm is used to numerically solve Newton's equations of motion. For the quantum CMD simualtions, adiabatic approxmation is employed where the light fictitious mass particles are assigned to all higher-order normal modes. This is very similar treatment to the path integral molecular dynamics.

** Results
The simulations are performed to explore both the equilibirum and dynamical properties associated with the proton transport. The quantum trajectories are obtained using CMD simulations. For the equilibrium properties, the excess proton microstructure in the environment of the solvating water molecules is determined using radial distribution function (RDF) both in the classical and quantum regime. RDF is computed for the excess charge carrying oxygen along with the oxygen from the water molecules for both the classical and quantum regimes. It is found that the quantum pair-correlation function showed a reduced peak and slightly broadened when compared to the classical function. These functions gives an intution of the environment surrounding the hydronium ion with water molecules forming first and second solvation shells. The stronger bonding of hydronium with the water molecule leads to the formation of eigen cation. This behaviour os observed for both the first and second solvation shells. The probability of finding an oxygen close to the hydronium ion at a give distance with in a quantum regime is more pronounced and the classical limit also approaches the limit. The RDF is also plotted for the non-hydronium carrying oxygens for both the classical and quantum regime. It is found that distribution functions are very much siimilar for both the regimes depicting that the classical MD simulations accurately treat the bulk water phase.

For the dynamical properties, proton transport pathway and rates are determined. The hopping rates are determined by the counting the number of hopping events from one hydronium to an another one and then by dividing over simulation time. It is an important fact the the proton osciallates during the transition and hence a successful hop event is only considered when the proton is localized with the new acceptor hydronium for more than a time period of 0.5ps after its transfer. Counting the hops gave a characteristic rates of 0.28 and 0.5 ps^{-1} for classical and quantum regime respectively. The other method used to determine the proton hopping rate is to use time correlation function formalism based on the Onsager's regression.

Proton transport pathways are always an important feature to investigate for determining dynamic properties. The excess proton which is an hydronium ion can be under the influence of eigen cation (H_{9}O_{4}^{+}) which is formed with the interactions of first solvation shell or the zundel cation (H_{5}O_{2}^{+}) which is a a water molecule strongly correlated with in the first solvation shell. The pathways are like excess charge transfer between two zundels or eigen cations. It is reported in the literature that both the pathways are observed in the dynamics of transport. The classical process of proton hopping from one eigen to an other eigen complex involves several oscillatory shuttling events between two water molecules and hence a successful hop events is only characterized by the time interval under observation and it is mostly chosen arbitrarily.The time scale is choosen based on the population autocorrelation function and it is found that the value of 0.38 ps^{-1} is found to be appropriate from the classical simulation. On the other hand, quantum CMD results indicated that the time interval of 0.69 ps^{-1} is appropriate which almost 2 times compared to the classical case. It is also stressed in this work that atleast more than two possible transfer channels exist, namely, zundel to eigen pathway or eigen to zundel pathway that could lead to a proton transport reaction in bulk water. It is reported that the intrinsic difficulties in defining the two species accurately in the dynamical process of interconversion makes it very difficult to address this issue.

** Conclusions
MS-EVB framework describing the proton transport reaction is established that allows one to model dynamical simulations and also to access trajectory length and time scales into much longer domains. This is made possible by the usage of low numerical cost of the potential functions that are accurately parameterized with the /ab-inito/ data using force fitting rather than energy fitting technique. Dynamical and structural properties of the excess proton in bulk water is investigated in this study using both classical and quantum mechanical simulations. For excess proton in bulk water, the pair correlation function is found to be in good agreement with the experimental results. The important finding in this study revealed that the quantum effects are negligible and the quantum dynamics reflect a very similar behavior to a classical, non-tunneling case.

** Critical Comments
MS-EVB classical molecular dynamics technique is evidently developed for faster resolution of proton transport reactions. It is not very clear how the transition of proton from one state to an other is treated in the off-diagonal elements of the hamiltonia with the damping function $A(r_{OO},q)$. This function can describe a localized treatment of the proton with either of the water molecules but not no explanation is provided for the treatment of transition state where the charge is mostly delocalized.

* Review - Proton Solvation and Transport in Hydrated Nafion
** Abstract
Proton solvation and transport properties are studied in hydrated nafion using classical molecular dynamics simulations. The predominant features focused in this paper is to compute diffusion rates, arrhenius activation energies, and proton transport pathways. Along with the transport properties, temperature and degree of water loading effects on the proton transport are investigated. 

Perfluorosulfonic acis (PESA) polymer membrane is a used as a state-of-the-art proton exchange membrane material for polymer electrolyte membrane fuel cell. This material exhibits higher proton transport (PT) rates along with mechanical and better chemical stability in reducing and oxidizing environments. Proton transport mechanism is not yet extensively studied with the addition of Nafion nano-structure and side-chain effects. It is also been found that the transport mechanism is strongly coupled to the water concentration. Computational methods such as molecular dynamics simulations are employed to understand the large scale effects on the proton solvation and transport in hydrated Nafion nanostructure.

In this review, the side-chain of the Nafion with the sufonate acid groups are considered as an important factor influencing the PT and received much of the study. Actication energies for proton transport reactions laong the surface with charged sulfonic groups are computed. It is also reported in the review that with the proton transport is facilitated by both vehicular and hopping mechanism. The most important findings suggested that the groutthuss hopping mechanism is dominant for proton transport in Nafion with water loading level between 5 to 10. 

** Methodology
Molecular dynamics simulations are performed with the trained MS-EVB potential parameterized to describe the bond breaking and making events. Vaious simulations are performed with a water loading of 6, 10 and 15 molecules of water per sulfonic acid group at different temperatures of 298, 320 and 340K. 
NPT simulations of 8 ns were carried out to relax the system to desired pressure of 1 atm and to attain appropriate density of water. Following the NPT simulation, NVT simulations are performed for 12 ns to equilibrate the system further to a desired set temeprature. The equilibrated structure from the above simulations are used for production runs of NVE ensemble for 1 ns for each of the water loading and at specific temperatures. The data is collected over an interval of 100fs. It should be important to note that much greater emphasis is given to the equilibrium phase of the simulation.
** Results
Proton solvation structure is investigated as it has been a major factor of interest in proton transport reactions. Radial Distribution functions (RDFs) is used as a tool to characterize the environment around the excess charge during the transition. Proton solvation structure is investigated for the excess charge close to the sulfur atoms in sulphonic acid groups in the Nafion side chains. In particular, RDFs are presented for the sulfur atoms of the nafion with hydrohium oxygen and the center for excess charge in the system. Center for excess charge (CEC) is defined as the weighted average of charge on the hydronium atoms relative to their positions. CEC characterizes the location of the center of delocalized proton charge defect and more physically an appropriate measure to track the location during grotthuss shuttling event. At a given water loading, the RDF correlations are established for the sulfur atom and the CEC at two different temperatures of 298K and 320K. It is found that at higher temperature, there is a strong correlation between sulfur and the CEC and this is mostly because of the loss of water molecules facilitating the hydrogen bonding with the excess charge defect. The RDFs are also plotted at 298K for the S atoms of the Nafion and the CEC at different hydration levels. The peaks tends to drop down with the increase of water loading. This is a result of stronger correlation of excess charge with more water molecules than with the sulfer atoms of Nafion. On the other hand, proton solvation structure stability is also investigated with the help of hydrogen bonding network. Hydrogen bonding network is analyzed with a distance and angle based criterion between two different oxygen atoms. When the distance is smaller than 3.5\AA and the angle is less than 30\deg between the two oxygen atoms, a hydrogen bond is likely to establish. Probability density is reported with respect to the angle (measured within excess charge and also with the oxygen atom establishing the hydrogen bond). It is found that the increasing the level of hydration causes nearly no changes to angle distribution. It is also reported that with increase of temperature, there is a very small change to the angle distribution for the proton related hydrogen bonded network.

Transport mechanism and properties are characterized using proton hopping direction and mean-squared displacement (MSD). Diffusion coefficients are computed using Einstein relation involving MSD. These results are also compared with the experimental measurements for temperatures of 298K and 340K. It is reported that the proton diffusion rates increases with the increase of hydration levels and temperatures. At lower temperatures, the simulation results of proton diffusion rates agree to a good extent with the experimental measurements, whereas at high temperatures, the simulation results are smaller than the experimental results. 

Activation energies are computed for the proton transport reaction at various hydration levels ranging from 6 to 15. As the temperature increases, the increase of diffusion rates are limited by the size and shape of the hydrophilic domians, resulting in lower activation energy. Similarly, the activation energy at higher hydration levels is slightly greater than the activation energy of PT in pure water system. The higher activation energy at higher water loading can be attributed to the strength of hydrogen bonding network between bulk water molecules.

Proton transport pathway is reported for the Nafion based system by exploring the proton hopping direction, distance and distribution of sulfonate groups and water molecules in the PT pathway. The proton hopping direction was calculated as a function of the distance to the closest sulfonate group. Hopping towards the sulfonate group is considered as "backward hop" whereas any other direction is considered as "forward hop". This is because proton transport facilitated by the sulphonate groups are much slower than in the bulk water phase in the nafion. Quantity /P(r)/, is defined as the ratio of number of backward hops (/N_{b}(r)/) with respect to the total number of hops, forward and back (/N_{f}(r) + N_{b}(r)/). All the hops are measured with respect to the shortest distance (/r/) between the CEC and the sulfur atoms in the sulfonate groups. /P(r)/ is determined of two different temperatures and also for different levels of hydration. This will quantify the influence of temperature and level of hydration to the proton hopping direction. /P(r)/ region is divided into two about a distance (/r_{m}/). Region /r < r_{m}/ indicates more backward hops towards sulfonate groups as it is obvious from the decrease of r between S atoms and the CEC. Within this region, the CEC is highly influenced by the first solvation shell of water molecules around the S atom of the sulfonic acid. The region /r > r_{m}/ signifies proton hop in the bulk water phase indicating forward transport. The interesting transition from backward hops to forwards hops takes place about the first solvation shell surrounding the S atoms in the sulfonic acid groups. With in the solvation shell, the CEC is highly influenced by the strong electrostatic interactions between sulfur atoms and the CEC facilitating more backward hops. On the other hand the net hopping direction shift from backward to forward as one moves outward of first solvation shell. This is because of the increased influence of water molecules establishing the hydrogen bonded network. Along with the proton hopping direction proton hopping distance is computed in the surface water region closer to the sulfonate groups as the proton hopping characterisitics are well known in the bulk water phase. The quantity dr, is defined as the distance travelled by the proton from leaving the first solvation shell of one sulfonate group to entering the first solvation shell of another sulfonate group. This value of dr is smaller than the average distance between the sulfonate groups. With the increase of water loading, the proton hopping distance (/dr/) increases as the sulfonate groups are seperated becuase of the seepage of water molecules between the sulfonate groups. At higher temperatures, there is no change observered to the distribution of /dr/, which indicates that the /dr/ is mostly influenced by the distribution of sulfonate groups. The distribution of sulfonate groups visited by the proton during a hopping event per time interval is an important measure of characterizing the influence of sulfonate groups in PT. It is found that increasing the water loading and with temperature results in more sulfonate groups visited by the proton during hopping that are closer to surface water regime. This is because of the water channel that connects the sulfonate groups and facilitates the transport of proton to visit more sulfonate groups near the surface water regime.

** Conclusions
It is demonstarted in this work that hydrated Nafion was simulated at different hydration levels and at different temperatures to investigate the excess proton solvation properties and transport mechanism. The solvation structure is found to be strongly influenced by the sulfonate groups. Temperature effects to the proton solvation structure is also reported to be influenced by around the vicinity of sulfonate groups. The distribution of angles for the proton related water network established the details on the stability of excessc charge. Transport properties like diffusion coefficients are estimated from the slope of MSDs and the results are found to be in good agreement with the experimental measurements. The activation energies are also measured for from the arrhenius expression using diffusion coefficients. It is found that the activation energy is greatly coupled with the level of hydration and also strongly influenced by the hydrophilic domain microstructure in the Nafion. Finally, PT pathways are analyzed based on the proton hopping direction, distance and the analysis of distribution of surrounding environment. The hopping direction is strongly influenced by the sulfonate groups and the distance travelled by the proton between the sulfonate groups is strongly coupled by the level of hydration. Temperature and water loading influences the proton to visit more sulfonate groups.

** Critical Comments
1. There is a slight disagreement of the proton diffusion rates computed at higher temperatures with that to the experimental results and no clear explanation is provided. 
2. Further explanation on different stages of equilibration (NPT & NVT) could have been better as equilibration period is very much longer than production run.

* Bibliography
# <<bibliographystyle>>
bibliographystyle:unsrt

# <<bibliography>>
bibliography:./references.bib
