#+TITLE: 24-623 2015 HM1
#+AUTHOR: Abhishek Bagusetty
#+LATEX_CLASS: cmu-article
#+OPTIONS: ^:{} # make super/subscripts only when wrapped in {}
#+OPTIONS: toc:nil # suppress toc, so we can put it where we want
#+OPTIONS: tex:t
#+EXPORT_EXCLUDE_TAGS: noexport

\maketitle

* Problem 1
** (i)
$$ 2x^6 - 3x^4 + 4x^2 - 3$$
For efficient calculations we can use the following,
$$  x^2 = x*x$$
$$  x^4 = x^2 * x^2$$
$$  x^6 = x^4 * x^2$$
This will minimize the number of FLOPS as well as any temporary variables created during the process.

** (ii)
Prime number is only divisible by one and itself. Hence we iterate and find any numbers that factor the variable there by tagging it as composite. Algorithm to find if a number is prime is performed by using a common *primality* algorithm :

1. The given number is tested if it is PERFECT SQUARE or not (the code for this is already provided). This information is used in the subsequent steps to search.
2. A set of numbers check if a given number is a factor.
3. If the number has a PERFECT SQUARE, we iterate all the numbers starting from 2 till the square of that number because the factors will be repeated anyway.
4. If the number is NOT a PERFECT SQUARE, we iterate all the number starting from 2 till the (number-1).
5. NOTE : We start iterations from 2 and only iterate odd numbers as the even numbers can be tested by 2. 

   
* Problem 2
** Paper 1: 
** Paper 2: 

* Problem 3
** (a)
Assumption : Water at NPT conditions

_Some mertics_

1 mole = 6.023.1E+23 molecules, 1 lit = 1E-24 $nm^3$

|--------------+----------------+--------------+------------+------------------|
| diameter(nm) | Volume$(nm^3)$ |        moles |  molecules | App. (molecules) |
|--------------+----------------+--------------+------------+------------------|
|            1 |      0.5238095 | 2.910052E-23 | 1.7527E+01 |               18 |
|           10 |       5.238095 | 2.910052E-22 | 1.7527E+02 |              180 |
|          100 |       52.38095 | 2.910052E-21 | 1.7527E+03 |             1800 |
|--------------+----------------+--------------+------------+------------------|

** (b)
The number of distinct interactions 


* Problem 4
** (a)

#+BEGIN_LaTeX
\begin{figure}[H]
\begin{centering}
\scalebox{0.75}{\includegraphics{./LJ-Ex4.png}}
\caption{LJ Potential}
\label{fig:fig1}
\end{centering}
\end{figure}
#+END_LaTeX

** (b)
\begin{equation}
\boxed{u(r) = 4\epsilon\Big[\big(\frac{\sigma}{r}\big)^{12}-\big(\frac{\sigma}{r}\big)^6\Big] \label{eq:1}}
\end{equation}

Setting u(r) = 0 in eqref:eq:1
$$\implies 0 = 4\epsilon\Big[\big(\frac{\sigma}{r}\big)^{12}-\big(\frac{\sigma}{r}\big)^6\Big]$$

\begin{equation}
\implies \big(\frac{\sigma}{r}\big)^6\Big[\big(\frac{\sigma}{r}\big)^6-1\Big] = 0 \label{eq:2})
\end{equation}

Roots of the eqref:eq:2, \underline{$r = \infty$} and \underline{$r = \sigma$}, at which $u(r)=0$.

For finding minimum for eqref:eq:1, set $\frac{du(r)}{dr} = 0$

\begin{equation}
\frac{du(r)}{dr} = 4\epsilon\Big[ \frac{-12\sigma^{12}}{r^{13}} + \frac{6\sigma^6}{r^7} \Big]
\end{equation}

\begin{equation}
\implies 4\epsilon\sigma^6 \Big[ \frac{-12\sigma^6}{r^{13}} + \frac{6}{r^7} \Big] = 0 \label{eq:3}
\end{equation}
$$\implies \frac{1}{r^7} \Big[ \frac{2\sigma^6}{r^6} - 1 \Big] = 0 $$

Root of eqref:eq:3, $r=\infty$ and $r = \qquad \sigma\sqrt[\leftroot{-1}\uproot{2}\scriptstyle 6]2\qquad$ at which $u(r)$ is at minimum.

\begin{equation}
\boxed{U_i(r_{nn}) = 2\epsilon\Big[A_{12}\Big(\frac{\sigma}{r_{nn}}\Big)^{12} - A_6\Big(\frac{\sigma}{r_{nn}}\Big)^6\Big] \label{eq:5}}
\end{equation}

Setting $U_i(r_{nn})$ = 0 in eqref:eq:5
$$\implies 0 =
2\epsilon\Big[A_{12}\Big(\frac{\sigma}{r_{nn}}\Big)^{12}-A_6\Big(\frac{\sigma}{r_{nn}}\Big)^6\Big] $$

\begin{equation}
\implies 2\epsilon\Big(\frac{\sigma^6}{r_{nn}}\Big) \Big[A_{12}\Big(\frac{\sigma}{r_{nn}}\Big)^{6} - A_6\Big] = 0 \label{eq:6}
\end{equation}

Roots of the eqref:eq:6, $r_{nn} = \infty$ and
$r_{nn} = \qquad \sigma \sqrt[\leftroot{-1}\uproot{2}\scriptstyle 6]{\frac{A_{12}}{A_6}}\qquad$ at which $U(r_{nn})=0$.

\newline
For finding minimum for eqref:eq:5, set $\frac{dU_i(r_{nn})}{dr_{nn}} = 0$

\begin{equation}
\frac{dU_i(r_{nn})}{dr_{nn}} = 2\epsilon\Big[ A_{12}\frac{-12\sigma^{12}}{r_{nn}^{13}} + A_6\frac{6\sigma^6}{r_{nn}^7} \Big]
\end{equation}

$$\implies -12\frac{\epsilon\sigma^6}{r_{nn}^7} \Big[ A_{12}\frac{\sigma^6}{r_{nn}^6} - A_6 \Big] = 0$$

\begin{equation}
\implies \frac{1}{r_{nn}^7} \Big[ A_{12}\frac{\sigma^6}{r_{nn}^6} - A_6 \Big] = 0 \label{eq:7}
\end{equation}

Root of eqref:eq:7, $r_{nn}=\infty$ and $r_{nn} = \qquad \sigma\sqrt[\leftroot{-1}\uproot{2}\scriptstyle 6]{\frac{2A_{12}}{A_6}}\qquad$ at which $U_i(r_{nn})$ is at minimum.

** (c)
$k_{LJ}$ is dimnesionless LJ thermal conductivity,

$$\boxed{k_{LJ} = \frac{k_B}{\sigma^2} \sqrt{\frac{\epsilon}{m}}}$$

** (d)
dimensionless temperature $(T^{*})$, 
$$ T = T^{*} \Big(\frac{\epsilon}{k_B}\Big) \implies T^{*} = \frac{T}{\epsilon/k_B} $$

dimensionless thermal conductivity $(k^{*})$, 
$$k = k^{*}\Big(\frac{k_B}{\sigma^2}\sqrt{\frac{\epsilon}{m}}\Big) \implies k^* = \frac{k}{\Big(\frac{k_B}{\sigma^2}\sqrt{\frac{\epsilon}{m}}\Big)}$$

_Argon_
*** Dimensionless Temperature
$$T^* = \frac{20K}{\frac{1.67.1E{-21}J}{1.3806.1E^{-23}J/K}}$$
$$\boxed{T^*_{Argon} = 0.1653}$$
*** Dimensionless thermal conductivity
$$k^* = \frac{1.4W/m-K}{\Big(\frac{1.3806.1E-23J/K}{(3.4.1E-10 m)^2}\sqrt{\frac{1.67.1E-21J}{6.63.1E-26 kg}}\Big)} $$
$$\boxed{k_{Argon}^{*} = 0.018955} $$
_Krypton_
*** Corresponding Temperature
$$T_{krypton} = T^*_{Argon} \Big(\epsilon/k_B\Big)$$
$$T = 0.1653K \Big(\frac{1.67.1E{-21}J}{1.3806.1E{-23}J/K}\Big)$$
$$\boxed{T_{krypton} = 26.82K}$$
*** Corresponding Thermal conductivity
$$k_{krypton} = k^*_{argon}\Big(\frac{k_B}{\sigma^2}\sqrt{\frac{\epsilon}{m}}\Big)$$

$$k = 0.018955 \Big(\frac{1.3806.1E-23J/K}{(3.65.1E-10 m)^2}\sqrt{\frac{2.24.1E-21J}{13.9.1E-26 kg}}\Big) $$

$$\boxed{k_{krypton} = 2.4935.1E-4   W/m-K} $$
